replicaCount: 1

image:
  repository: docker.io/jackzhang412/springboot-demo
  tag: map[.freight.springboot-demo.tag:<nil>]
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: []
